// Compatibility wrapper around the canonical implementation.

module "platform" {
  source = "../../platforms/azure-functions"

  name_prefix                             = var.name_prefix
  environment                             = var.environment
  location                                = var.location
  tags                                    = var.tags
  image                                   = var.image
  deployment_slot_enabled                 = var.deployment_slot_enabled
  deployment_slot_name                    = var.deployment_slot_name
  deployment_slot_image                   = var.deployment_slot_image
  container_port                          = var.container_port
  plan_sku_name                           = var.plan_sku_name
  admin_password                          = var.admin_password
  skip_migrations                         = var.skip_migrations
  db_admin_username                       = var.db_admin_username
  db_admin_password                       = var.db_admin_password
  existing_db_fqdn                        = var.existing_db_fqdn
  existing_db_connection_string           = var.existing_db_connection_string
  db_name                                 = var.db_name
  db_sku_name                             = var.db_sku_name
  db_storage_mb                           = var.db_storage_mb
  db_version                              = var.db_version
  db_public_network_access                = var.db_public_network_access
  db_firewall_start_ip                    = var.db_firewall_start_ip
  db_firewall_end_ip                      = var.db_firewall_end_ip
  db_geo_redundant_backup_enabled         = var.db_geo_redundant_backup_enabled
  enable_postgis                          = var.enable_postgis
  additional_env                          = var.additional_env
  redis_connection_string                 = var.redis_connection_string
  redis_enabled                           = var.redis_enabled
  redis_sku_name                          = var.redis_sku_name
  redis_family                            = var.redis_family
  redis_capacity                          = var.redis_capacity
  redis_enable_non_ssl_port               = var.redis_enable_non_ssl_port
  redis_public_network_access_enabled     = var.redis_public_network_access_enabled
  redis_subnet_id                         = var.redis_subnet_id
  registry_server                         = var.registry_server
  registry_username                       = var.registry_username
  registry_password                       = var.registry_password
  app_insights_enabled                    = var.app_insights_enabled
  functions_extension_version             = var.functions_extension_version
  functions_worker_runtime                = var.functions_worker_runtime
  storage_account_tier                    = var.storage_account_tier
  storage_account_replication_type        = var.storage_account_replication_type
  storage_network_default_action          = var.storage_network_default_action
  serve_admin_ui                          = var.serve_admin_ui
  key_vault_public_network_access_enabled = var.key_vault_public_network_access_enabled
  db_backup_retention_days                = var.db_backup_retention_days
}
