#!/usr/bin/env bash
# Copyright (c) Honua. All rights reserved.
# Licensed under the Elastic License 2.0. See LICENSE in the project root.
#
# Seed the client-compat `test_service` layer into the live demo stack.
#
# This is the SDK client-compat certification target consumed by the
# honua-sdk-python staging smoke (honua-sdk-python#53): service `test_service`,
# a single Point layer whose attribute set is {objectid, name, description,
# status, count, ratio, uid, active}. It is ADDITIVE — it never touches the
# Maui showcase layers.
#
# Why not apply honua-server's tests/seed/client-compat-v1.sql directly?
# That fixture rebuilds the metadata-v2 snapshot as revision 1 from its own
# shim tables, which on this shared, admin-published, multi-tenant stack would
# clobber the live Production snapshot (currently rev 40+) and drop the Maui
# services. Instead we mirror exactly how the Maui layers were seeded: create
# a physical PostGIS table via the in-VPC postgis-bootstrap Lambda (the RDS
# instance is only reachable in-VPC), then PUBLISH it through the server's own
# admin API, which incrementally adds the layer to the activated snapshot
# (new revision, Maui preserved) and materializes public.features.
#
# Requirements: awscli + curl + python3; IAM rights to invoke the
# postgis-bootstrap Lambda and read the admin-password secret; the demo admin
# API reachable at $BASE_URL.
#
# Usage:
#   ./seed-test-service.sh                 # seed (idempotent)
#   BASE_URL=https://demo.honua.io ./seed-test-service.sh
set -euo pipefail

REGION="${AWS_REGION:-us-west-2}"
NAME_PREFIX="${NAME_PREFIX:-honua-demo}"
ENVIRONMENT="${ENVIRONMENT:-demo}"
BOOTSTRAP_FN="${BOOTSTRAP_FN:-${NAME_PREFIX}-${ENVIRONMENT}-postgis-bootstrap}"
ADMIN_SECRET="${ADMIN_SECRET:-${NAME_PREFIX}-${ENVIRONMENT}/admin-password}"
BASE_URL="${BASE_URL:-https://demo.honua.io}"
CONNECTION_ID="${CONNECTION_ID:-4f468b76-9937-4835-9e64-ddc8012b30c1}" # demo-rds secure connection
SERVICE_NAME="${SERVICE_NAME:-test_service}"
TABLE="${TABLE:-test_service_features}"

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

echo "==> 1/3 create + seed public.${TABLE} via ${BOOTSTRAP_FN}"
python3 - "$tmp/create.json" <<'PY'
import json, sys
stmts = [
 'CREATE TABLE IF NOT EXISTS public.test_service_features ('
 ' objectid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,'
 ' name text, description text, status text, "count" integer,'
 ' ratio double precision, uid text, active boolean,'
 ' geometry geometry(Point,4326))',
 'CREATE INDEX IF NOT EXISTS idx_tsf_geom ON public.test_service_features USING GIST(geometry)',
 'INSERT INTO public.test_service_features (name,description,status,"count",ratio,uid,active,geometry) '
 'SELECT * FROM (VALUES '
 "('alpha',NULL::text,'active',1,1.25,'00000000-0000-0000-0000-000000000001',true,ST_SetSRID(ST_MakePoint(-122.49,37.71),4326)),"
 "('beta','description_1','inactive',2,2.50,'00000000-0000-0000-0000-000000000002',false,ST_SetSRID(ST_MakePoint(-122.475,37.72),4326)),"
 "('gamma','description_2','active',3,3.75,'00000000-0000-0000-0000-000000000003',true,ST_SetSRID(ST_MakePoint(-122.46,37.73),4326)),"
 "('delta',NULL,'inactive',4,5.00,'00000000-0000-0000-0000-000000000004',false,ST_SetSRID(ST_MakePoint(-122.445,37.74),4326)),"
 "('epsilon','description_4','active',5,6.25,'00000000-0000-0000-0000-000000000005',true,ST_SetSRID(ST_MakePoint(-122.43,37.75),4326)),"
 "('zeta','description_5','inactive',6,7.50,'00000000-0000-0000-0000-000000000006',false,ST_SetSRID(ST_MakePoint(-122.415,37.76),4326)),"
 "('eta',NULL,'active',7,8.75,'00000000-0000-0000-0000-000000000007',true,ST_SetSRID(ST_MakePoint(-122.40,37.77),4326)),"
 "('theta','description_7','inactive',8,10.00,'00000000-0000-0000-0000-000000000008',false,ST_SetSRID(ST_MakePoint(-122.385,37.78),4326)),"
 "('iota','description_8','active',9,11.25,'00000000-0000-0000-0000-000000000009',true,ST_SetSRID(ST_MakePoint(-122.37,37.79),4326)),"
 "('lambda',NULL,'inactive',10,12.50,'00000000-0000-0000-0000-000000000010',true,ST_SetSRID(ST_MakePoint(-122.355,37.80),4326))"
 ') AS v(name,description,status,count,ratio,uid,active,geometry) '
 'WHERE NOT EXISTS (SELECT 1 FROM public.test_service_features)'
]
json.dump({"statements": stmts,
           "query": "SELECT count(*)::text FROM public.test_service_features"},
          open(sys.argv[1], "w"))
PY
aws lambda invoke --region "$REGION" --function-name "$BOOTSTRAP_FN" \
  --cli-binary-format raw-in-base64-out --payload "file://$tmp/create.json" \
  "$tmp/create.out" >/dev/null
python3 -c "import json;print('    rows:',json.load(open('$tmp/create.out')).get('rows'))"

PW="$(aws secretsmanager get-secret-value --region "$REGION" --secret-id "$ADMIN_SECRET" --query SecretString --output text)"

echo "==> 2/3 publish ${SERVICE_NAME} via admin API"
cat > "$tmp/publish.json" <<JSON
{"schema":"public","table":"${TABLE}","layerName":"Test Layer","description":"Client compatibility certification layer","geometryColumn":"geometry","geometryType":"Point","srid":4326,"primaryKey":"objectid","fields":["objectid","name","description","status","count","ratio","uid","active"],"serviceName":"${SERVICE_NAME}","enabled":true}
JSON
publish_out="$(curl -fsS -X POST -H "X-API-Key: $PW" -H "Content-Type: application/json" \
  -d @"$tmp/publish.json" \
  "${BASE_URL}/api/v1/admin/connections/${CONNECTION_ID}/layers" || true)"
echo "    $publish_out"
layer_id="$(printf '%s' "$publish_out" | python3 -c 'import sys,json;print(json.load(sys.stdin).get("data",{}).get("layerId",""))' 2>/dev/null || true)"

echo "==> 3/3 enable anonymous read on ${SERVICE_NAME}"
curl -fsS -X PUT -H "X-API-Key: $PW" -H "Content-Type: application/json" \
  -d '{"allowAnonymous":true}' \
  "${BASE_URL}/api/v1/admin/services/${SERVICE_NAME}/access-policy" >/dev/null
echo "    done."

echo
echo "test_service published. FeatureServer layer id: ${layer_id:-<see publish output>}"
echo "Set HONUA_LAYER_ID in the honua-sdk-python 'staging' environment to this id."
echo "NOTE: FeatureServer applyEdits (write smoke) needs the Pro"
echo "      'editing.featureserver-edits' entitlement; the demo runs Community"
echo "      edition, so the SDK write smoke is opt-out on this target."
