// Compatibility wrapper around the canonical implementation.

module "platform" {
  source = "../../platforms/aws-serverless"

  name_prefix                           = var.name_prefix
  environment                           = var.environment
  tags                                  = var.tags
  vpc_cidr                              = var.vpc_cidr
  public_subnet_cidrs                   = var.public_subnet_cidrs
  private_subnet_cidrs                  = var.private_subnet_cidrs
  existing_vpc_id                       = var.existing_vpc_id
  existing_vpc_cidr                     = var.existing_vpc_cidr
  existing_public_subnet_ids            = var.existing_public_subnet_ids
  existing_private_subnet_ids           = var.existing_private_subnet_ids
  enable_nat_gateway                    = var.enable_nat_gateway
  image                                 = var.image
  lambda_memory_size                    = var.lambda_memory_size
  lambda_timeout_seconds                = var.lambda_timeout_seconds
  lambda_ephemeral_storage_mb           = var.lambda_ephemeral_storage_mb
  lambda_architectures                  = var.lambda_architectures
  lambda_reserved_concurrent_executions = var.lambda_reserved_concurrent_executions
  lambda_alias_name                     = var.lambda_alias_name
  lambda_alias_version                  = var.lambda_alias_version
  admin_password                        = var.admin_password
  skip_migrations                       = var.skip_migrations
  db_username                           = var.db_username
  db_password                           = var.db_password
  db_name                               = var.db_name
  db_instance_class                     = var.db_instance_class
  db_allocated_storage                  = var.db_allocated_storage
  db_publicly_accessible                = var.db_publicly_accessible
  db_additional_ingress_cidrs           = var.db_additional_ingress_cidrs
  db_multi_az                           = var.db_multi_az
  db_require_ssl                        = var.db_require_ssl
  existing_db_endpoint                  = var.existing_db_endpoint
  existing_db_connection_string         = var.existing_db_connection_string
  enable_postgis                        = var.enable_postgis
  postgis_readiness_max_attempts        = var.postgis_readiness_max_attempts
  postgis_readiness_sleep_seconds       = var.postgis_readiness_sleep_seconds
  additional_env                        = var.additional_env
  redis_connection_string               = var.redis_connection_string
  redis_connection_cidrs                = var.redis_connection_cidrs
  redis_auth_token                      = var.redis_auth_token
  redis_enabled                         = var.redis_enabled
  redis_node_type                       = var.redis_node_type
  redis_engine_version                  = var.redis_engine_version
  redis_parameter_group_name            = var.redis_parameter_group_name
  redis_num_cache_clusters              = var.redis_num_cache_clusters
  redis_port                            = var.redis_port
  log_retention_days                    = var.log_retention_days
  single_nat_gateway                    = var.single_nat_gateway
  api_throttle_burst_limit              = var.api_throttle_burst_limit
  api_throttle_rate_limit               = var.api_throttle_rate_limit
  cors_allowed_origins                  = var.cors_allowed_origins
  db_engine_version                     = var.db_engine_version
  serve_admin_ui                        = var.serve_admin_ui
}
