#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=./lib/tf-secret-catalog.sh
source "$SCRIPT_DIR/lib/tf-secret-catalog.sh"
DEFAULT_ENV_FILE="$SCRIPT_DIR/tf-secrets.local.sh"
DEFAULT_REPO="honua-io/honua-terraform"

usage() {
  cat <<'EOF'
Usage:
  scripts/bootstrap-gh-secrets.sh [options]

Options:
  --repo <owner/repo>      Target repository for gh secrets (default: honua-io/honua-terraform)
  --env-file <path>        Shell file with exported vars (default: scripts/tf-secrets.local.sh)
  --write-template <path>  Write an env template and exit
  --dry-run                Print what would be set without writing secrets
  -h, --help               Show this help

Examples:
  scripts/bootstrap-gh-secrets.sh --dry-run
  scripts/bootstrap-gh-secrets.sh
  scripts/bootstrap-gh-secrets.sh --write-template ./tf-secrets.local.sh
  scripts/tf-pass-secrets.sh sync-gh --scope publish --repo honua-io/honua-server
EOF
}

write_template() {
  local output="$1"
  {
    echo "#!/usr/bin/env bash"
    echo "# Generated by scripts/bootstrap-gh-secrets.sh"
    echo "# Fill in values, then run:"
    echo "#   scripts/bootstrap-gh-secrets.sh --env-file \"$output\""
    echo "# Or import into pass and load from there with:"
    echo "#   scripts/tf-pass-secrets.sh import --env-file \"$output\""
    echo
    for key in "${TERRAFORM_ESSENTIAL_SECRETS[@]}"; do
      echo "export $key=\"\""
    done
    echo
    for key in "${TERRAFORM_OPTIONAL_SECRETS[@]}"; do
      echo "export $key=\"\""
    done
  } > "$output"
  chmod 600 "$output"
  echo "Template written: $output"
}

assert_gh_ready() {
  if ! command -v gh >/dev/null 2>&1; then
    echo "error: gh CLI not found" >&2
    exit 1
  fi
  if ! gh auth status >/dev/null 2>&1; then
    echo "error: gh CLI not authenticated; run 'gh auth login'" >&2
    exit 1
  fi
}

main() {
  local repo="$DEFAULT_REPO"
  local env_file="$DEFAULT_ENV_FILE"
  local dry_run=0
  local template_path=""

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --repo)
        repo="${2:-}"
        shift 2
        ;;
      --env-file)
        env_file="${2:-}"
        shift 2
        ;;
      --write-template)
        template_path="${2:-}"
        shift 2
        ;;
      --dry-run)
        dry_run=1
        shift
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      *)
        echo "error: unknown option '$1'" >&2
        usage
        exit 1
        ;;
    esac
  done

  if [[ -n "$template_path" ]]; then
    write_template "$template_path"
    exit 0
  fi

  assert_gh_ready

  if [[ ! -f "$env_file" ]]; then
    echo "error: env file not found: $env_file" >&2
    echo "hint: create one with --write-template, or copy scripts/tf-secrets.local.example.sh" >&2
    exit 1
  fi

  set -a
  # shellcheck source=/dev/null
  source "$env_file"
  set +a

  local -a all_keys
  all_keys=("${TERRAFORM_ESSENTIAL_SECRETS[@]}" "${TERRAFORM_OPTIONAL_SECRETS[@]}")

  local -a missing_essential=()
  local -a missing_optional=()
  local -a updated=()

  for key in "${all_keys[@]}"; do
    local value="${!key:-}"
    if ! tf_secret_value_is_present "$value"; then
      if tf_secret_contains "$key" "${TERRAFORM_ESSENTIAL_SECRETS[@]}"; then
        missing_essential+=("$key")
      else
        missing_optional+=("$key")
      fi
      continue
    fi

    if [[ "$dry_run" -eq 1 ]]; then
      updated+=("$key")
      continue
    fi

    gh secret set "$key" --repo "$repo" --body "$value" >/dev/null
    updated+=("$key")
  done

  if [[ "$dry_run" -eq 1 ]]; then
    echo "Dry run: would set ${#updated[@]} secrets in $repo"
  else
    echo "Set ${#updated[@]} secrets in $repo"
  fi

  if [[ ${#updated[@]} -gt 0 ]]; then
    printf 'Updated: %s\n' "${updated[@]}"
  fi

  if [[ ${#missing_essential[@]} -gt 0 ]]; then
    printf 'Missing essential: %s\n' "${missing_essential[@]}" >&2
    exit 2
  fi

  if [[ ${#missing_optional[@]} -gt 0 ]]; then
    printf 'Missing optional: %s\n' "${missing_optional[@]}"
  fi
}

main "$@"
